# Generated by Django 5.0 on 2024-01-08 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='classModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('fatherName', models.CharField(max_length=150)),
                ('motherName', models.CharField(max_length=150)),
                ('roll', models.IntegerField()),
                ('className', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.classmodel')),
            ],
        ),
    ]
