# Generated by Django 5.0 on 2024-01-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='className',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='className',
            field=models.ManyToManyField(to='student.classmodel'),
        ),
    ]
